pipeline:
- name: undistort
  mess: '---Perform optical undistortion---'
- name: colorcarddetect
  mess: '---Perform color card detection---'
- name: colorcorrect
  mess: '---Perform color correction---'
- name: traydetect
  mess: '---Perform tray detection---'
- name: potdetect
  mess: '---Perform pot detection---'
- name: imagewrite
  mess: '---Write image---'
  outstream: -cor
- name: plantextract
  mess: ---Performing plant segmentation---
- name: imagewrite
  mess: ---Writing Image---
  outstream: -seg
  masked: True
- name: featureextract
  mess: ---Extract Plant Features---
  features: ["all"]
- name: writefeatures
  mess: ---Writing Features---

outstreams:
  - { name: -seg }
  - { name: -cor }

general:
  #startDate: { year: 2014, month: 06, day: 25, hour: 9, minute: 0, second: 0}
  #endDate: {}
  #startHourRange: { hour: 9, minute: 0, second: 0}
  #endHourRange: { hour: 15, minute: 0, second: 0}
  #timeInterval: 900
  visualise: False
